# Generated by Django 4.2 on 2025-04-09 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_userquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserQuestion',
        ),
    ]
