# Generated by Django 4.2 on 2025-04-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_delete_userquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', '🆕 Принят'), ('assembling', '🛠️ В сборке'), ('packed', '📦 Упакован'), ('on_way', '🚚 В пути'), ('delivered', '✅ Доставлен'), ('canceled', '❌ Отменён'), ('postponed', '⏸️ Перенесён'), ('problem', '❗ Проблема'), ('ready_for_pickup', '🏪 Готов к самовывозу')], default='accepted', max_length=20, verbose_name='Статус'),
        ),
    ]
